### PR TITLE
Move mocks package to src/test

### PR DESCRIPTION
**Pull request by wborn**
Mocks should only be used in test code and not in production.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Could you please rebase this PR?

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
Shit, it now needs another rebase! 🙄

**Comment by wborn** [comment]
I try to do the PRs such that they don't conflict with eachother but sometimes it doesn't work out like that. :wink:

**Pull request merged**
