### PR TITLE
Revive documentation

### LINKED ISSUE #215: Documentation missing from website
It would be nice when the documentation in `docs` was published on the [website](https://www.jupnp.org/) so it can be more easily read.
It looks like previously the Maven Site Plug-in used the XHTML files when generating the website.

Did you already have some plans for the documentation @kaikreuzer?

Perhaps the docs are easier to read and maintain when they are converted to Markdown?

There are also many [`// DOC:` markers](https://github.com/search?q=repo%3Ajupnp%2Fjupnp+%22%2F%2F+DOC%3A%22&type=code) in the code which may be removed depending on how the documentation will be created. These markers seem to be only used by [Lemma](http://4thline.org/projects/lemma/manual/lemma-manual.xhtml).

The original Cling documentation is still available here:
http://4thline.org/projects/cling/core/manual/cling-core-manual.xhtml

### PR DESCRIPTION
**Pull request by wborn**
* Migrate documentation from XHTML to Markdown
* Remove Lemma markers from code
* Deploy documentation to Docusaurus v3 website

Fixes #215

---

See https://jupnp.maindrain.net/ for what this [Docusaurus](https://docusaurus.io/) based website will look like.

Having the website in the same branch makes it possible to update the documentation in the same PR as code changes.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Looks awesome!
Are you still working on this PR or shall I glance over the docs and merge it?

**Comment by wborn** [comment]
Would be nice if you can have a look!
It has everything I wanted to add for now. 😉 

You'll probably also need to change the GitHub pages settings to use GitHub Actions on the main branch. I don't have permission to change that.

**Comment by kaikreuzer** [comment]
FTR: Merged as "rebase and merge" to keep the 3 commits in place.

**Comment by kaikreuzer** [comment]
Website successfully deployed!

>  I don't have permission to change that.

I changed the maintainers' role from "maintain" to "admin" - so you should now also be able to change that.

**Comment by wborn** [comment]
Thanks for the new permissions and nice that the website is deployed!

The diagrams were already part of the repo. I only made them semi transparant to fix issues in dark mode and optimized the PNGs.

Might be worth a try to see if they can be redrawn using Mermaid syntax which is supported by Docusaurus:

https://docusaurus.io/docs/next/markdown-features/diagrams

**Pull request merged**
