### PR TITLE
Ignore HTTPS requests

### LINKED ISSUE #109: NPE if https scheme is used by a UPnP device in the network
If certain Samsung devices are on the local network, jUPnP logs errors like

```
2018-09-16 23:05:03.295 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@7c95d877 failed
    java.lang.NullPointerException: Missing SslContextFactory
    at java.util.Objects.requireNonNull(Objects.java:228) ~[?:?]
    at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.&lt;init&gt;(SslClientConnectionFactory.java:50) ~[74:org.eclipse.jetty.io:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1155) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:138) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpDestination.&lt;init&gt;(HttpDestination.java:95) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.PoolingHttpDestination.&lt;init&gt;(PoolingHttpDestination.java:25) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.&lt;init&gt;(HttpDestinationOverHTTP.java:32) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:51) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:539) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:572) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:680) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:149) [210:org.jupnp:2.4.0]
    at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:1) [210:org.jupnp:2.4.0]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
    at java.lang.Thread.run(Thread.java:748) [?:?]
```
As it seems, jUPnP does not support https at all, but is expected to call a https url in this situation.
I haven't experienced any https in UPnP networks myself so far.
Even if the default SSL context were added to Jetty, I assume that requests would fail due to the impossibility to verify the certificate (which must be a self-signed one as there's no defined domain name for the device).
To circumvent this, we would probably have to add a custom trust manager, which simply accepts all certificates unseen.
If anybody has a better idea how to address this, please comment!

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #109

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer for review

**Comment by kaikreuzer** [comment]
Hm, this suppresses the error, but it does not really fix the issue.
As mentioned in #109, I believe the proper fix would be to "add a custom trust manager, which simply accepts all certificates unseen."
By not following the url, we do not properly support the discovered device.

**Comment by lolodomo** [comment]
I was expecting this remark from you and I should admit you are righjt ;)
This PR was an attempt to find a quick solution for @morph166955 problem.
As I am not concerned directly by this problem and more important I have no way to reproduce it, I am sorry but I will not invest more free time on that.

**Comment by kaikreuzer** [comment]
Well, I didn't say I wouldn't merge this PR, I only said that it does not fix the issue it claims to fix.
If it helps us to suppress the exception, we can go for it, I am just not sure if it would also justify a new UPnP release...

**Pull request closed without merging**
