### PR TITLE
Disable all UPnP action calls based on HTTPS - Fixed #109

### LINKED ISSUE #109: NPE if https scheme is used by a UPnP device in the network
If certain Samsung devices are on the local network, jUPnP logs errors like

```
2018-09-16 23:05:03.295 [ERROR] [org.jupnp.transport.spi.StreamClient] - Request: HttpRequest[GET /capability HTTP/1.1]@7c95d877 failed
    java.lang.NullPointerException: Missing SslContextFactory
    at java.util.Objects.requireNonNull(Objects.java:228) ~[?:?]
    at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.&lt;init&gt;(SslClientConnectionFactory.java:50) ~[74:org.eclipse.jetty.io:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1155) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:138) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpDestination.&lt;init&gt;(HttpDestination.java:95) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.PoolingHttpDestination.&lt;init&gt;(PoolingHttpDestination.java:25) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.&lt;init&gt;(HttpDestinationOverHTTP.java:32) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.http.HttpClientTransportOverHTTP.newHttpDestination(HttpClientTransportOverHTTP.java:51) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.destinationFor(HttpClient.java:539) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:572) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:680) ~[70:org.eclipse.jetty.client:9.4.11.v20180605]
    at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:149) [210:org.jupnp:2.4.0]
    at org.jupnp.transport.impl.jetty.JettyStreamClientImpl$1.call(JettyStreamClientImpl.java:1) [210:org.jupnp:2.4.0]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
    at java.lang.Thread.run(Thread.java:748) [?:?]
```
As it seems, jUPnP does not support https at all, but is expected to call a https url in this situation.
I haven't experienced any https in UPnP networks myself so far.
Even if the default SSL context were added to Jetty, I assume that requests would fail due to the impossibility to verify the certificate (which must be a self-signed one as there's no defined domain name for the device).
To circumvent this, we would probably have to add a custom trust manager, which simply accepts all certificates unseen.
If anybody has a better idea how to address this, please comment!

### PR DESCRIPTION
**Pull request by morph166955**
Disable all UPnP action calls based on HTTPS - Fixed #109

Signed-off-by: morph166955 <rosenblumb@gmail.com>

### CODE REVIEW

**Comment by morph166955** [comment]
Example logs...

Before:

```
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Preparing HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Creating HTTP request. URI: 'https://REDACTED:8888/capability' method: 'GET'
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Waiting 2 seconds for HTTP request to complete: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.757 [TRACE] [org.jupnp.transport.spi.StreamClient] - Sending HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-16 20:39:18.758 [WARN ] [org.jupnp.transport.spi.StreamClient] - HTTP request failed: (StreamRequestMessage) GET https://REDACTED:8888/capability
```

After:

```
2021-03-17 02:01:18.980 [TRACE] [org.jupnp.transport.spi.StreamClient] - Preparing HTTP request: (StreamRequestMessage) GET https://REDACTED:8888/capability
2021-03-17 02:01:18.989 [DEBUG] [org.jupnp.transport.spi.StreamClient] - HTTPS invalid.  Ignoring call https://REDACTED:8888/capability.

```

**Comment by kaikreuzer** [comment]
Hm, this looks very similar to https://github.com/jupnp/jupnp/pull/127, therefore my [same comment](https://github.com/jupnp/jupnp/pull/127#issuecomment-733221333) applies here as well: Suppressing an error is not the same as fixing an error for me. I'd much prefer to actually support the https scheme (I assume that it is allowed wrt the UPnP spec?). Have you checked what it would take to actually perform the request correctly?

**Comment by morph166955** [comment]
As far as I have ever seen, https is actually not part of the UPnP spec.  In fact, I'm pretty sure the spec intends for you to NOT use https at all.  This makes sense because when a device is put on a local network there is no way for the manufacturer to do anything other than a self signed certificate (because there is no dns resolvable hostname and in many cases it's just straight IP).  We would have to accept all self-signed certs and do a bunch of other things to make this work.  Also, since upnp is supposed to be restricted to your local subnet, security isn't as much of a concern as traffic that would fly across the internet.  I did go looking for a specific entry in the spec that discusses this and I couldn't find anything in either direction.  The only thing I've ever seen that attempts to use https in upnp are a few random Samsung devices (like my fridge).

**Comment by kaikreuzer** [comment]
It is clear that one cannot verify certificates in a local network, but encrypting traffic can also be of value by itself.

I've found http://upnp.org/specs/gw/UPnP-gw-DeviceProtection-V1-Service.pdf, which states in chapter 2.3.1:

> To add security while preserving compatibility with legacy Control Points, root Devices and embedded
Devices that directly contain the DeviceProtection service MUST include the SSDP extension header
SECURELOCATION.UPNP.ORG in addition to the normal SSDP LOCATION URL. Both of these URLs
MUST point to the same device description document but with different port numbers. 

I assume that we only deal with `LOCATION` and for those it seems you are right that they must be HTTP and never HTTPS. 
Supporting UPnP DeviceProtection in jUPnP is definitely out of scope for us.

Do you happen to see where your Samsung provide the http urls?
Would it maybe be an alternative fix to change the scheme from https to http, so that we could actually support those devices instead of ignoring them?

**Comment by morph166955** [comment]
I'll try to do a PCAP of the packets coming from my fridge to identify the HTTP URL.  I've never actually seen one come in through debugs but maybe it's buried somewhere in there.

**Comment by morph166955** [comment]
I have done a PCAP on the packet.  It is a single SSDP NOTIFY packet that comes from the fridge.  There is no http URL in the payload that we could attempt to read.  The payload is as follows (with a few pieces redacted for my security):

NOTIFY * HTTP/1.1
NT: urn:SmartHomeAlliance-org:device:Refrigerator:1.5 deviceSubType/Refrigerator modelID/TP6X_REF_16K
NTS: ssdp:alive
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age = 1800
USN: uuid:REDACTED-0000-0000-000000000000::urn:SmartHomeAlliance-org:device:Refrigerator:1.5 deviceSubType/Refrigerator modelID/TP6X_REF_16K
SERVER: Linux/2.6 SHP/1.0 Refrigerator/1.5 deviceSubType/Refrigerator modelID/TP6X_REF_16K
LOCATION: https://REDACTED:8888/capability

**Comment by kaikreuzer** [comment]
Thanks, excellent that you were able to capture it that quickly!

So I'd agree then. The device does not behave according to the spec and we can ignore the url.
Instead of doing debug logging, I would suggest to use the `SpecificationViolationReporter`, which was introduced with https://github.com/jupnp/jupnp/pull/68, so that people who want violations to be strictly logged will get this one included.

**Comment by morph166955** [comment]
@kaikreuzer I believe that should do the trick on this.  Please doublecheck that I implemented SpecificationViolationReporter properly, I've not used it before.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thank you!

**Pull request merged**
